# Generated by Django 5.2.14 on 2026-05-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tast',
            new_name='Task',
        ),
    ]
